### PR TITLE
update TGP page

### PR DESCRIPTION
**Pull request by johnwbryant**
A few edits to the TGP page. There will be more, no doubt :)

### CODE REVIEW

**Comment by alpha-beta-soup** [comment]
Want me to add an "apply" button as well (as mentioned in Slack)?

**Comment by alpha-beta-soup** [comment]
Screenshot from 2019-05-31 11-52-39

Also worth noting that the Markdown parser is extremely literal and I cannot find any way to ignore any comments left in the Markdown (not even a `<span style="display:none;">Comment</span>`). So I took out the "tbc tito" remark.

**Comment by johnwbryant** [comment]
That would be sweet!

**Comment by alpha-beta-soup** [comment]
Done, it's live now. https://2019.foss4g-oceania.org/tgp

**Pull request merged**
